name: Packaging

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools setuptools_scm twine wheel
    - name: Create packages
      run: python setup.py sdist bdist_wheel
    - name: Run twine check
      run: twine check dist/*
    - uses: actions/upload-artifact@v2
      with:
        name: django-ordered-model-dist
        path: dist
    - name: Run twine upload
      env: 
        TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
      if: env.TWINE_PASSWORD != null
      run: twine upload --username __token__ --non-interactive --repository testpypi 


